### ISSUE TITLE
ERDを作成する

### ISSUE THREAD

**Issue by mackeee-orange** [toshi0228/yorozu#1]
![IMG_17B028A67321-1](https://user-images.githubusercontent.com/12053974/71248657-bfccf600-235e-11ea-8f0f-cf290e074c75.jpeg)

これくらいの雑さでいいので、ERDを書いてみましょう
https://it-koala.com/entity-relationship-diagram-1897
これのアトリビュートのない版と思ってもらえれば！

**Comment by toshi0228** [comment]
￼￼

**Comment by toshi0228** [comment]
![ER図](https://user-images.githubusercontent.com/52807235/72148551-7cf1c180-33e4-11ea-8ce8-698b9ef15526.jpg)

**Comment by toshi0228** [comment]
![File](https://user-images.githubusercontent.com/52807235/72148810-102af700-33e5-11ea-8a9a-988826e9ce75.jpg)

**Comment by mackeee-orange** [comment]
Planを受講する。という状態をPlanをそのまま持つ。ということはできません。
なぜなら
PlanテーブルがUserに所属するということはuser_idを外部キーとして持つ。ということになるのですが、受講する全員のuser_idを持つことができないからです。
なのでこのように中間テーブルを挟みます
![IMG_0712](https://user-images.githubusercontent.com/12053974/72199028-4ca83280-3479-11ea-99af-15acc335c686.PNG)
@toshi0228

**Comment by toshi0228** [comment]
![File (1)](https://user-images.githubusercontent.com/52807235/72343699-d292da80-3712-11ea-879f-72b2e7777bfb.jpg)
